server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-service

eureka:
  client:
    #true表示向服务中心注册自己
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息 默认为true
    #单节点无所谓 集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务需要依赖这个地址
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka/
      #集群版
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#  instance:
#    instance-id: payment8001
#    prefer-ip-address: true #访问路径可以显示ip地址


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
