#consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&charactEncoding=utf-8&useSSL=false
    username: root
    password: lj210910

#consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname:127.0.0.1
        service-name: ${spring.application.name}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lingjian.springcloud.entities  #所有Entity别名类所在包

  #开启驼峰命名匹配
  configuration:
    map-underscore-to-camel-case: true
