server:
  port: 8001
spring:
  application:
    name: cloud-payment-service

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于0到1之间 1表示全部采集
      probability: 1

  #设置DataSource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&charactEncoding=utf-8&useSSL=false
    username: root
    password: lj210910
eureka:
  client:
    #true表示向服务中心注册自己
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息 默认为true
    #单节点无所谓 集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务需要依赖这个地址
      #单机版
      defaultZone: http://localhost:7001/eureka/
      #集群版
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示ip地址

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lingjian.springcloud.entities  #所有Entity别名类所在包

  #开启驼峰命名匹配
  configuration:
    map-underscore-to-camel-case: true


