server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider

  cloud:
    stream:
      #配置要绑定的rabbitmq的服务消息
      binders:
        #表示定义的名称 用于binding整合
        defaultRabbit:
          #消息组件类型
          type: rabbit
          #设置rabbitmq的相关配置环境
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      #服务整合处理
      bindings:
        #是一个通道的名字
        output:
          #表示要使用Exchange名称定义
          destination: studyExchange
          #设置消息类型
          content-type: application/json
          #设置要绑定消息服务的具体设置
          binder: defaultRabbit


eureka:
  client:
    #true表示向服务中心注册自己
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息 默认为true
    #单节点无所谓 集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    #设置心跳时间间隔（默认30s）
    lease-renewal-interval-in-seconds: 2
    #如果现在超过5s的间隔（默认90s）
    lease-expiration-duration-in-seconds: 5
    #在消息列表中显示主机名称
    instance-id: send-8801.com
    #访问的路径变为IP地址
    prefer-ip-address: true
