server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
          #payment_route #路由ID没有固定规则但要求唯一 建议配合服务名
        - id: payment_route
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          #匹配后提供服务的微服务名路由地址
          uri: lb://cloud-payment-service
          #断言 路径匹配的进行路由
          predicates:
            - Path=/payment/get/**
          #payment_route #路由ID没有固定规则但要求唯一 建议配合服务名
        - id: payment_route2
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          #匹配后提供服务的微服务名路由地址
          uri: lb://cloud-payment-service
          #断言 路径匹配的进行路由
          predicates:
            - Path=/payment/lb/**
#            - After=2020-04-03T16:58:49.274+08:00[Asia/Shanghai]
            #要带上Cookie "username=lingjian"
#            - Cookie=username,lingjian
            #请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Header=X-Request-Id, \d+
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能 利用微服务名进行路由
          enabled: true
      default-filters:
        #过滤器工厂会在匹配的请求头上加一对请求头 名称为X-Request-Id 值为1024
        - AddRequestParameter=X-Request-Id,1024


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        #集群版
#        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#        单机版
      defaultZone: http://eureka7001.com:7001/eureka/
