server:
  port: 80

#spring:
#  application:
#    name: cloud-consumer-order

eureka:
  client:
    register-with-eureka: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务需要依赖这个地址
      #集群版
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka/


#  为false则超时控制有ribbon控制
#  为true则看hystrix超时和ribbon超时，谁小谁生效，默认为true
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: false
#        isolation:
#          thread:
#            #熔断器的超时时长默认1秒，最常修改的参数
#            timeoutInMilliseconds: 5000
ribbon:
  #建立连接后从服务器读取到可用资源所用的时间 处理请求的超时时间 默认1秒
  ReadTimeout: 10000
  #建立连接所用的时间 适用于网络状况正常的情况 两端连接所用的时间
  #连接建立的超时时长，默认1秒
  ConnectTimeout: 10000

#用于服务降级
feign:
  hystrix:
    enabled: true


