server:
  port: 80

#spring:
#  application:
#    name: cloud-consumer-order

eureka:
  client:
    register-with-eureka: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务需要依赖这个地址
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#设置feign客户端超时时间(OpenFeign默认支持ribbon）
ribbon:
  #建立连接后从服务器读取到可用资源所用的时间
  readTimeout: 5000
  #建立连接所用的时间 适用于网络状况正常的情况 两端连接所用的时间
  ConnectTimeout: 5000



logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.lingjian.springcloud.service.PaymentFeignService: debug
