spring:
  datasource:
   username: root
   password: lj210910
   url: jdbc:mysql://182.92.124.128:3306/jdbc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
   driver-class-name: com.mysql.cj.jdbc.Driver
   initialization-mode: always
   schema:
     - classpath:sql/department.sql
