spring:
  datasource:
    username: root
    password: lj210910
    url: jdbc:mysql://192.168.0.126:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


#    initialization-mode: always
#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql

mybatis:
  configuration:
    map-underscore-to-camel-case: true
